version: '3.8'

services:
  # -----------------------------------
  # 1. MySQL Service
  # -----------------------------------
  mysql:
    image: mysql:8.0
    container_name: mysql-kotlin-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: study
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # -----------------------------------
  # 2. Spring Boot Service
  # -----------------------------------
  kotlin-api:
    container_name: kotlin-api-container
    build:
      context: ../../              # [핵심 변경] 프로젝트 최상위 루트로 변경
      dockerfile: kotlin/kotlin-api/Dockerfile # [핵심 변경] Dockerfile 위치 지정
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/study?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: on-failure